.TH image_to_j2k 1 "February 19, 2008" "image_to_j2k 1.1.1" "OpenJPEG Reference Manual"
.SH NAME
\fB
\fBimage_to_j2k \- convert a PNM, PGM, PPM, PGX or BMP into a J2K or JP2 file
\fB
.SH SYNOPSIS
.nf
.fam C

\fBimage_to_j2k\fP \fB\-i\fP \fIsource\fP \fB\-o\fP \fIdestination\fP [\fB\-cinema2k\fP] [\fB\-cinema4k\fP] [\fB\-r\fP \fIratios\fP | \fB\-q\fP \fIpsnr\fP] [\fB\-n\fP \fIrescount\fP] [\fB\-b\fP \fIblocksize\fP] [\fB\-c\fP \fIprecintsize\fP] [\fB\-t\fP \fItilesize\fP] [\fB\-p\fP \fIprogression\fP] [\fB\-s\fP \fIsubsampling\fP] [\fB\-POC\fP \fIorders\fP] [\fB\-SOP\fP] [\fB\-EPH\fP] [\fB\-M\fP \fImodeflags\fP] [\fB\-x\fP \fIindexfile\fP] [\fB\-ROI\fP:quantize] [\fB\-d\fP \fIimageoffset\fP] [\fB\-T\fP \fItileoffset\fP] [\fB\-I\fP]
\fBimage_to_j2k\fP \fB\-ImgDir\fP \fIsourcedir\fP \fB\-OutFor\fP \fIextension\fP [\fB\-cinema2k\fP] [\fB\-cinema4k\fP] [\fB\-r\fP \fIratios\fP | \fB\-q\fP \fIpsnr\fP] [\fB\-n\fP \fIrescount\fP] [\fB\-b\fP \fIblocksize\fP] [\fB\-c\fP \fIprecintsize\fP] [\fB\-t\fP \fItilesize\fP] [\fB\-p\fP \fIprogression\fP] [\fB\-s\fP \fIsubsampling\fP] [\fB\-POC\fP \fIorders\fP] [\fB\-SOP\fP] [\fB\-EPH\fP] [\fB\-M\fP \fImodeflags\fP] [\fB\-x\fP \fIindexfile\fP] [\fB\-ROI\fP:quantize] [\fB\-d\fP \fIimageoffset\fP] [\fB\-T\fP \fItileoffset\fP] [\fB\-I\fP]
\fBimage_to_j2k\fP \fB\-h\fP
.fam T
.fi
.SH DESCRIPTION

\fBimage_to_j2k\fP converts an image into a JPEG 2000\-encoded image
.SH OPTIONS

.TP
.B
\fB\-ImgDir\fP {\fIsourcedir\fP}
Directory of PGM, PPM, PNM, PGX or BMP files to convert
.TP
.B
\fB\-OutFor\fP {\fIextension\fP}
J2K or JP2 output file format
.TP
.B
\fB\-i\fP {\fIsource\fP}
PNM, PGM or PPM file to convert
.TP
.B
\fB\-o\fP {\fIdestination\fP}
J2K or JP2 file to output to
.TP
.B
\fB\-h\fP
Display help information 
.TP
.B
\fB\-cinema2k\fP {fps}
Digital Cinema 2K profile compliant codestream for 2K resolution. 24 or 48 fps.
.TP
.B
\fB\-cinema4k\fP [fps]
Digital Cinema 4K profile compliant codestream for 4K resolution. fps default is 24
.TP
.B
\fB\-r\fP {\fIratios\fP}
compression factor for successive layers, comma seperated
.TP
.B
\fB\-q\fP {\fIpsnr\fP}
\fIpsnr\fP for successive layers, comma seperated
.TP
.B
\fB\-n\fP {\fIrescount\fP}
number of resolutions
.TP
.B
\fB\-b\fP {\fIblocksize\fP}
width and height of code block, comma\-seperated
.TP
.B
\fB\-c\fP {\fIprecintsize\fP}
width and height of precinct, comma\-seperated
.TP
.B
\fB\-t\fP {\fItilesize\fP}
width and height of tile, comma\-seperated
.TP
.B
\fB\-p\fP {\fIprogression\fP}
\fIprogression\fP order, one of LRCP, RLCP, RPCL, PCRL, CPRL
.TP
.B
\fB\-s\fP {\fIsubsampling\fP}
\fIsubsampling\fP factor in X and Y, comma\-seperated. Values larger than 2 can produce errors
.TP
.B
\fB\-POC\fP {\fIorders\fP}
\fIprogression\fP order change
.TP
.B
\fB\-SOP\fP
write SOP marker before each packet 
.TP
.B
\fB\-EPH\fP
write EPH marker after each header packet 
.TP
.B
\fB\-M\fP {\fImodeflags\fP}
Sum of the values of the modes, as follows:
.RS
.IP 1. 4
BYPASS (LAZY)
.IP 2. 4
RESET
.IP 4. 4
RESTART (TERMALL)
.IP 8. 4
VSC
.IP 16. 4
ERTERM (SEGTERM)
.IP 32. 4
SEGMARK (SEGSYM)
.RE
.TP
.B
\fB\-x\fP {\fIindexfile\fP}
create an index file
.TP
.B
\fB\-ROI\fP:{quantize}
quantization indices upshifted for component c between 0 and 2 inclusive with an upshift of U between 0 and 37 inclusive
.TP
.B
\fB\-d\fP {\fIimageoffset\fP}
X and Y offset of the origin of the image, comma\-seperated
.TP
.B
\fB\-T\fP {\fItileoffset\fP}
X and Y offset of the origin of the tiles, comma\-seperated
.TP
.B
\fB\-I\fP
use the irreversible DWT 9\-7
.SH EXAMPLE

.TP
.B
\fIratios\fP: 20,10,1
Quality 1: compress 20x; Quality 2: compress 10x; Quality 3: lossless compression
.TP
.B
\fIpsnr\fP: 30,40,50
.PP
quantize: c=0,U=25
.TP
.B
\fIorders\fP: T1=0,0,1,5,3,CPRL
Title 1: Resolution 0 start, component 0 start, layer 1 end, resolution 5 end, component 3 end, CPRL \fIprogression\fP
.SH AUTHOR

Written by Paul Hampson <Paul.Hampson@Pobox.com> based on the output of \fBimage_to_j2k\fP \fB\-h\fP as part of the Debian packaging of OpenJPEG
.SH COPYRIGHT

Copyright 2007 Paul Hampson
.SH SEE ALSO

\fBj2k_to_image\fP(1), http://www.openjpeg.org/index.php?menu=doc#encoder
