=head1 NAME

j2k_to_image - convert a J2K, JP2 or JPT file into a PGM, PPM, PNM, PGX or BMP file


=head1 SYNOPSIS

B<j2k_to_image> B<-i> I<source> B<-o> I<destination> [B<-r> I<reduction>] [B<-l> I<layers>]

B<j2k_to_image> B<-ImgDir> I<sourcedir> B<-OutFor> I<extension> [B<-r> I<reduction>] [B<-l> I<layers>]

B<j2k_to_image> B<-h>


=head1 DESCRIPTION

j2k_to_image decodes a JPEG 2000-encoded image into another image format


=head1 OPTIONS

=over

=item B<-ImgDir> I<sourcedir>

Directory of J2K, JP2 or JPT files to convert

=item B<-OutFor> I<extension>

PGM, PPM, PNM, PGX or BMP output file format

=item B<-i> I<source>

J2K, JP2 or JPT file to convert

=item B<-o> I<destination>

PGM, PPM, PNM, PGX or BMP file to output to

=item B<-h>

Display help information

=item B<-r> I<reduction>

Number of highest resolution levels to be discarded. Output resolution is effectively divided by 2^reduction

=item B<-l> I<layers>

Maximum count of quality layers to decode

=back


=head1 AUTHOR

Written by Paul Hampson <Paul.Hampson@Pobox.com> based on the output of j2k_to_image -h as part of the Debian packaging of OpenJPEG


=head1 COPYRIGHT

Copyright 2007 Paul Hampson


=head1 SEE ALSO

L<image_to_j2k(1)>, L<http://www.openjpeg.org/index.php?menu=doc#decoder>
