.TH j2k_to_image 1 "February 19, 2008" "j2k_to_image 1.1.1" "OpenJPEG Reference Manual"
.SH NAME
\fB
\fBj2k_to_image \- convert a J2K, JP2 or JPT file into a PGM, PPM, PNM, PGX or BMP file
\fB
.SH SYNOPSIS
.nf
.fam C

\fBj2k_to_image\fP \fB\-i\fP \fIsource\fP \fB\-o\fP \fIdestination\fP [\fB\-r\fP \fIreduction\fP] [\fB\-l\fP \fIlayers\fP]
\fBj2k_to_image\fP \fB\-ImgDir\fP \fIsourcedir\fP \fB\-OutFor\fP \fIextension\fP [\fB\-r\fP \fIreduction\fP] [\fB\-l\fP \fIlayers\fP]
\fBj2k_to_image\fP \fB\-h\fP
.fam T
.fi
.SH DESCRIPTION

\fBj2k_to_image\fP decodes a JPEG 2000\-encoded image into another image format
.SH OPTIONS

.TP
.B
\fB\-ImgDir\fP {\fIsourcedir\fP}
Directory of J2K, JP2 or JPT files to convert
.TP
.B
\fB\-OutFor\fP {\fIextension\fP}
PGM, PPM, PNM, PGX or BMP output file format
.TP
.B
\fB\-i\fP {\fIsource\fP}
J2K, JP2 or JPT file to convert
.TP
.B
\fB\-o\fP {\fIdestination\fP}
PGM, PPM, PNM, PGX or BMP file to output to
.TP
.B
\fB\-h\fP
Display help information 
.TP
.B
\fB\-r\fP {\fIreduction\fP}
Number of highest resolution levels to be discarded. Output resolution is effectively divided by 2^\fIreduction\fP
.TP
.B
\fB\-l\fP {\fIlayers\fP}
Maximum count of quality \fIlayers\fP to decode
.SH AUTHOR

Written by Paul Hampson <Paul.Hampson@Pobox.com> based on the output of \fBj2k_to_image\fP \fB\-h\fP as part of the Debian packaging of OpenJPEG
.SH COPYRIGHT

Copyright 2007 Paul Hampson
.SH SEE ALSO

\fBimage_to_j2k\fP(1), http://www.openjpeg.org/index.php?menu=doc#decoder
